#!/bin/bash -e
# qsotime - Script zur Berechnung der Sendezeit
# by DL7ATA
# V 1.0	Juli 2018
#
# Das Script ist zur Auswertung von 2 Logiken ausgelegt
#
#------indiv. Anpassung -------------------------------
# Ausgabedatei für Auswertung
file_prefix="/home/svxlink/svx-log/svx_qsotime"
# Logdatei
datei="/var/log/svxlink"
# Schlüsselbegriffe aus dem Log
tx1="70cmTx: Turning the transmitter"
tx2="2mTx: Turning the transmitter"
#-----------------------------------------------------
#
d=$(date +%y%m%d.%H%M%S)
declare -i z1
declare -i z2
zeitOFF=""
zeitON=""
file=${file_prefix}.$d
beginn=$(head -n1 $datei | cut -c1-19)
ende=$(tail -n1 $datei | cut -c1-19)
echo "Log beginnt: $beginn" > $file

while read variable;do

   #prüfen Tx1 (70cm)
   if [[ "$variable" == *"$tx1"* ]] ; then
   	if [[ "$variable" == *"ON"* ]]; then
	   zeitON=$(echo $variable | cut -c12-19)
	   #in UNIX umwandeln
	   zeiton=`date --utc --date "$zeitON" +%s`

	else

	 #prüfen ob Log mit TX off beginnt - dann fehlt sinnvoller Inhalt von $zeitON
	 if [[ "$zeitON" != "" ]]; then
	    zeitOFF=$(echo $variable | cut -c12-19)
	    #in UNIX umwandeln
	    zeitoff=`date --utc --date "$zeitOFF" +%s`
	    tt1=$(echo $(($zeitoff-$zeiton)))
	    z1=$(($z1+$tt1))
	 fi
       fi
   fi


   #prüfen Tx2 (2m)
   if [[ "$variable" == *"$tx2"* ]] && [[ "$zeitOFF" != "" ]]; then
   	if [[ "$variable" == *"ON"* ]]; then
	   zeitON=$(echo $variable | cut -c12-19)
	   #in UNIX umwandeln
	   zeiton=`date --utc --date "$zeitON" +%s`

	else

	 if [[ "$zeitON" != "" ]]; then
	    zeitOFF=$(echo $variable | cut -c12-19)
	    #in UNIX umwandeln
	    zeitoff=`date --utc --date "$zeitOFF" +%s`
	    tt2=$(echo $(($zeitoff-$zeiton)))
	    z2=$(($z2+$tt2))
	fi
      fi
   fi

done < $datei

echo "Log endet:   $ende" >> $file
z11="$(printf '%02d' "$z1")"
z12="$(printf '%02d' "$z2")"
echo "70cm: $((z1 /3600)) std $((z1 % 3600 /60)) min $((z1 % 60)) s" >> $file
echo "2m  : $((z2 /3600)) std $((z2 % 3600 /60)) min $((z2 % 60)) s" >> $file

#echo "insgesamt " $((($z1/60/60)+($z2/60/60))) "Stunden" >> $file

exit 0
